admin_webo_sidemap:
  path: webosidemapgenerator
  methods: [GET]
  defaults:
    _controller: 'WeboSidemapGenerator\controller\AdminaWeboSideMapGeneratorController::showMainPanel'
    _legacy_controller: 'AdminaWeboSideMapGeneratorController'