admin_webo_sidemap:
  path: webosidemapgenerator
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\WeboSidemapGenerator\Controller\Admin\AdminWeboSideMapGeneratorController::configurationAction'