services:
  _defaults:
    public: true

  prestashop.module.webo_sidemapgenerator.form.configurationtype:
    class: 'PrestaShop\WeboSidemapGenerator\Form\ConfigurationType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.webo_sidemapgenerator.form.configuration_data_provider:
    class: 'PrestaShop\WeboSidemapGenerator\Form\ConfigurationFormDataProvider'
    arguments:
      - '@prestashop.module.webo_sidemapgenerator.form.configuration_data_configuration'

  prestashop.module.webo_sidemapgenerator.form.configuration_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.webo_sidemapgenerator.form.configuration_data_provider'
      - 'PrestaShop\WeboSidemapGenerator\Form\ConfigurationType'
      - 'Configuration'

  prestashop.module.webo_sidemapgenerator.form.configuration_data_configuration:
    class: PrestaShop\WeboSidemapGenerator\Form\ConfigurationDataConfiguration
    arguments: [ '@prestashop.adapter.legacy.configuration' ]

#  prestashop.module.demosymfonyform.form.type.demo_configuration_choice:
#    class: 'PrestaShop\Module\DemoSymfonyForm\Form\DemoConfigurationChoiceType'
#    parent: 'form.type.translatable.aware'
#    public: true
#    tags:
#      - { name: form.type }
#
#  prestashop.module.demosymfonyform.form.demo_configuration_choice_form_data_provider:
#    class: 'PrestaShop\Module\DemoSymfonyForm\Form\DemoConfigurationChoiceFormDataProvider'
#    arguments:
#      - '@prestashop.module.demosymfonyform.form.demo_configuration_choice_data_configuration'
#
#  prestashop.module.demosymfonyform.form.demo_configuration_choice_form_data_handler:
#    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
#    arguments:
#      - '@form.factory'
#      - '@prestashop.core.hook.dispatcher'
#      - '@prestashop.module.demosymfonyform.form.demo_configuration_choice_form_data_provider'
#      - 'PrestaShop\Module\DemoSymfonyForm\Form\DemoConfigurationChoiceType'
#      - 'DemoConfiguration'
        #  prestashop.module.demosymfonyform.form.type.demo_configuration_choice:
        #    class: 'PrestaShop\Module\DemoSymfonyForm\Form\DemoConfigurationChoiceType'
        #    parent: 'form.type.translatable.aware'
        #    public: true
        #    tags:
        #      - { name: form.type }
        #
#
#  prestashop.module.demosymfonyform.form.demo_configuration_choice_data_configuration:
#    class: PrestaShop\Module\DemoSymfonyForm\Form\DemoConfigurationChoiceDataConfiguration
#    arguments: [ '@prestashop.adapter.legacy.configuration' ]
#  prestashop.module.webo_sidemapgenerator.form.settings_data_configuration:
#    class: PrestaShop\WeboSidemapGenerator\Form\ConfigurationDataConfiguration
#    arguments: [ '@prestashop.adapter.legacy.configuration' ]
#
#  prestashop.module.webo_sidemapgenerator.form.settings_data_provider:
#    class: 'PrestaShop\WeboSidemapGenerator\Form\ConfigurationDataFormDataProvider'
#    arguments:
#      - '@prestashop.module.webo_sidemapgenerator.form.settings_data_configuration'
#
#  prestashop.module.webo_sidemapgenerator.form.configuration_data_handler:
#    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
#    arguments:
#      - '@form.factory'
#      - '@prestashop.core.hook.dispatcher'
#      - '@prestashop.module.webo_sidemapgenerator.form.settings_data_provider'
#      - 'PrestaShop\WeboSidemapGenerator\Form\ConfigurationType'