services:
  _defaults:
    public: true

  prestashop.module.webo_sidemapgenerator.form.settings_data_configuration:
    class: PrestaShop\WeboSidemapGenerator\Form\ConfigurationDataConfiguration
    arguments: [ '@prestashop.adapter.legacy.configuration' ]

  prestashop.module.webo_sidemapgenerator.form.settings_data_provider:
    class: 'PrestaShop\WeboSidemapGenerator\Form\ConfigurationDataFormDataProvider'
    arguments:
      - '@prestashop.module.webo_sidemapgenerator.form.settings_data_configuration'

  prestashop.module.webo_sidemapgenerator.form.configuration_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.webo_sidemapgenerator.form.settings_data_provider'
      - 'PrestaShop\WeboSidemapGenerator\Form\ConfigurationType'