<?php

namespace Prestashop\Module\WeboSidemapGenerator\Form;

use PrestaShopBundle\Form\Admin\Type\SwitchType;
use PrestaShopBundle\Form\Admin\Type\TranslatorAwareType;
use Symfony\Component\Form\FormBuilderInterface;

class SettingsType extends TranslatorAwareType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('active', SwitchType::class, [
                'required' => false,
                'label' => $this->trans('Activate Module', 'Admin.WeboSidemapGenerator.Admin'),
                'help' => $this->trans('If this module is active', 'Admin.WeboSidemapGenerator.Admin')
            ]);
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function getBlockPrefix()
    {
        return 'webo_sitemap_config';
    }

}